# Generated by Django 4.1.4 on 2022-12-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailydrip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='usage',
            field=models.IntegerField(),
        ),
    ]
